repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace

    -   repo: https://github.com/psf/black
        rev: 21.12b0
        hooks:
        -   id: black
            language_version: python3
            args: [ '-l 100' ]

    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v5.9.3
        hooks:
            -   id: isort

    -   repo: local
        hooks:
            -   id: pydoc
                name: pydocstyle
                exclude: 'tests'
                entry: pydocstyle
                language: system
                files: \.py$

    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            files: \.py$
            exclude: (.*versions.*|.*_examples\.py$|setup.py)
            args: [ "--rcfile=.pylintrc" ]

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.910
        hooks:
            -   id: mypy
                verbose: true
                exclude: 'tests'
                additional_dependencies:
                    - 'types-python-dateutil'

    - repo: local
      hooks:
          - id: message-format
            name: message-format
            entry: .commands/pre-commit-msg-hook.sh
            language: script
            stages: [ commit-msg ]
            always_run: True
